const IWorkflowEngine = require('../ports/IWorkflowEngine');
const fs = require('fs');
const path = require('path');
class FileWorkflowEngineAdapter extends IWorkflowEngine {
  constructor() { super(); this.WORKFLOW_DIR = path.join(__dirname, '../../workflows'); if (!fs.existsSync(this.WORKFLOW_DIR)) fs.mkdirSync(this.WORKFLOW_DIR, { recursive: true }); }
  initiate(title, description, initiator, steps = []) { const id = `WF-${Date.now()}`; const wf = { id, title, description, initiator, status: 'initiated', createdAt: new Date().toISOString(), steps: steps.length ? steps : [{ name: 'discussion', status: 'pending', required: true },{ name: 'dcp', status: 'pending', required: true },{ name: 'council', status: 'pending', required: false },{ name: 'approval', status: 'pending', required: true },{ name: 'deployment', status: 'pending', required: false },{ name: 'certification', status: 'pending', required: false },{ name: 'complete', status: 'pending', required: false }], currentStep: 0, artifacts: [], discussion: [] }; fs.writeFileSync(path.join(this.WORKFLOW_DIR, `${id}.json`), JSON.stringify(wf, null, 2)); return wf; }
  advanceStep(workflowId, stepName, artifact = null) { const file = path.join(this.WORKFLOW_DIR, `${workflowId}.json`); if (!fs.existsSync(file)) return { error: 'Workflow not found' }; const wf = JSON.parse(fs.readFileSync(file, 'utf-8')); const idx = wf.steps.findIndex(s => s.name === stepName); if (idx === -1 || wf.steps[idx].status === 'completed') return { error: `Step "${stepName}" not applicable` }; wf.steps[idx].status = 'completed'; wf.steps[idx].completedAt = new Date().toISOString(); if (artifact) wf.artifacts.push({ step: stepName, artifact, timestamp: new Date().toISOString() }); if (wf.steps.filter(s => s.required && s.status !== 'completed').length === 0) { wf.status = 'completed'; wf.completedAt = new Date().toISOString(); } fs.writeFileSync(file, JSON.stringify(wf, null, 2)); return { success: true, workflow: wf }; }
  addDiscussion(workflowId, seatId, message) { const file = path.join(this.WORKFLOW_DIR, `${workflowId}.json`); if (!fs.existsSync(file)) return { error: 'Workflow not found' }; const wf = JSON.parse(fs.readFileSync(file, 'utf-8')); wf.discussion.push({ seatId, message, timestamp: new Date().toISOString() }); wf.steps[0].status = 'in-progress'; fs.writeFileSync(file, JSON.stringify(wf, null, 2)); return { success: true, workflow: wf }; }
  listWorkflows() { if (!fs.existsSync(this.WORKFLOW_DIR)) return []; return fs.readdirSync(this.WORKFLOW_DIR).filter(f => f.endsWith('.json')).map(f => JSON.parse(fs.readFileSync(path.join(this.WORKFLOW_DIR, f), 'utf-8'))).sort((a, b) => b.createdAt.localeCompare(a.createdAt)); }
  getWorkflow(id) { const file = path.join(this.WORKFLOW_DIR, `${id}.json`); return fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, 'utf-8')) : null; }
}
module.exports = FileWorkflowEngineAdapter;